### ISSUE TITLE
为什么用您的数据集跑您的程序得出的结果却和您的结果不一样呢？

### ISSUE THREAD

**Issue by KajiMaCN** [longyahui/GCNMDA#3]
使用您的数据集结果train loss和train acc 都在下降 这是什么原因呢？请问博主有出现这种情况吗？

**Comment by VIVEK-RB** [comment]
hi sir, 
how did you run the program?
what are the 'train_data'  and 'test_data' in main.py ????
how to make 'train_data' and "test_data" ???

**Comment by KajiMaCN** [comment]
> hi sir,
> how did you run the program?
> what are the 'train_data' and 'test_data' in main.py ????
> how to make 'train_data' and "test_data" ???

you can use the data from adj.txt to run this program. 'train_data' and "test_data" all from adj.txt. but when i run this,another problem happened，i dont know how to slove.
